# Configuraciones para desarrollo
spring:
  devtools:
    restart:
      enabled: true
  config:
    #    Se importa otro archivo de configuraciones
    import: eventlistenerproperties.yml
  main:
    log-startup-info: true

app:
  enabled: false
  remote-address: 127.0.0.1
  security:
    user: "dev-user"
    password: "dev-password"
