# Configuraciones por default y aqui se define que archivo y bean debe cargar.
spring:
  devtools:
    restart:
      enabled: true
  config:
    #    Se importa otro archivo de configuraciones
    import: eventlistenerproperties.yml
  main:
    log-startup-info: true
  output:
    ansi:
      enabled: always
#debug: true
#trace: true
# Configurar archivos de salida de los logs
logging:
  file:
    name: "./logs/mylogs.log"
#    path: "./logs/"

#  profiles:
#    active: "dev"

app:
  enabled: false
  remote-address: 121.0.0.1
  security:
    user: "dev-user"
    password: "dev-password"
